### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by samii00** [NicholasSheehan/Unity-Native-Example-Project#1]
unity error on open project :cant find some file in unity-native-sharing ....
i check folder and it is empty
then i make a new unity project and add "git link" in package.jcon and can built it and run on android but when press **share button** nothing happen

**Comment by NicholasSheehan** [comment]
In order to keep the test project up to date and to test new changes, the plugin files aren't stored directly with this repo, instead, they are submodules so when one plugin is updated in its own repo, we can update it here with a simple commit.

The plugins are added to the `Unity-Project` though local packages, which can be updated and tested upon locally without having to commit anything, making development a lot easier and a lot quicker

---

Are there any files in `/Unity-Native-Sharing` or `/Unity-Native-Toasts`?

If not try running this git command in the root of the git repo

`git submodule update --init --recursive`

---

As for the `Unity-Native-Sharing`  issue. If the issue still persists, make an issue on that repo and include as much detail as possible

Edit: This repo is not intended to be pulled through the package manager of Unity, only the individual plugins

**Comment by NicholasSheehan** [comment]
Ill be closing this issue if soon due to lack of activity

**Comment by NicholasSheehan** [comment]
Closed due to inactivity
